### ISSUE TITLE
Not compatible with dot net core 1.1

### ISSUE THREAD

**Issue by daveriedstra** [jburzynski/TypeGen#1]
Is dotnet core compatibility on the roadmap for this project? I would love to use it. Thanks!

```
Errors in C:\Users\[REDACTED].xproj
    Package TypeGen 1.4.1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package TypeGen 1.4.1 supports: net (.NETFramework,Version=v0.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.1.
```

**Comment by jburzynski** [comment]
Hi Dave, thanks for your feedback!

.NET Core compatibility hasn't been a top priority up to this point - the main focus was put on adding new functionality.

However, now that nearly all planned functionality has been implemented, I could look into making it work cross-platform. This library mostly uses basic .NET framework functionality, so it should be possible to make it target .NET Core / .NET Standard without major changes.

I'll try to figure it out by the end of this week; in the meantime, I'll post any updates in this thread.

**Comment by daveriedstra** [comment]
Thanks, @jburzynski, I really appreciate it. Looking forward to hearing your results.

**Comment by jburzynski** [comment]
A little update after a week:

I've managed to successfully port the code to .NET Standard. Also, there are no nuget/compilation errors when adding the local NuGet package to a .NET Core / .NET Standard project (so the original issue seems to be resolved).

There are, however, still some errors when running TypeGen command from PM console. These errors are related to some system assemblies not being found. I will probably be able to resolve this issue relatively quickly (I'm guessing 1-2 days), so in a few days there should be a fully functional new version.

Right now, if you don't want to use the CLI (i.e. only want to use TypeGen.Core in your code), you could install a NuGet package that is currently on the dev branch (TypeGen.Core should be working, it's just the CLI that still has problems).

But if you also intend to use the CLI, I'd need to fix the aforementioned issue first.

Thanks for your patience, sorry I haven't been able to fix it yet ;)
I'll post any updates as soon as I get this working.

**Comment by jburzynski** [comment]
I'm happy to announce that TypeGen 1.5.0 has just been released, which provides support for .NET Standard 1.3. This means that you can install it if you have a .NET Core 1.x or .NET 4.6 application (for .NET < 4.6 support, you can still use TypeGen 1.4.1, which has essentially the same functionality).

If you're getting an error when installing the NuGet package, saying that it's incompatible with .NET Core, you may execute this command to clear the NuGet cache: `./nuget.exe locals -clear all`

If you're using CLI with a .NET Core app, you probably also need to add this to your **tgconfig.json**:
`"externalAssemblyPaths": ["C:/Users/[user_name]/.nuget/packages"]`
This will allow to load NuGet dependencies when reading the project's assembly, as they cannot be resolved automatically.

Also, please ignore the "build not passing" icon on the main page for the time being. It's because AppVeyor doesn't recognise Visual Studio 2017 RC projects.

In case of any problems/questions not related to this topic, please raise another issue or contact me on e-mail.

Hope the new version works well! ;)

**Comment by daveriedstra** [comment]
This is fantastic, thank you so much! I'm having having some troubles getting the CLI to work, possibly related to VS2015. I'll email you about it.
