### ISSUE TITLE
Optional properties are ignored

### ISSUE THREAD

**Issue by parloti** [jburzynski/TypeGen#101]
The following code in C # ...

`public int? ParentId { get; set; }`

... results in the following in Typescript ...

`parentId: number;`

... while the correct one should be:

`parentId?: number;`

**Comment by jburzynski** [comment]
Could you paste the definition of the C# type, the content of the generated TS file, the configuration (tgconfig.json) and the generation spec (if used)?

I'm not sure right now if this is a problem with the tool or the configuration, additional information would help determine the problem.

Thanks

**Comment by parloti** [comment]
I am only using the attribute in classes in C#, I have not used any additional configuration.

**C#**
```
using System.Collections.Generic;
using TypeGen.Core.TypeAnnotations;

namespace Business
{
    [ExportTsClass(OutputDir = @"../Presentation/ClientApp/src/app/models")]
    public class CommentDTO
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public ICollection<int> AnswerIds { get; set; }
        public int? ParentId { get; set; }
        public int ActivityId { get; set; }
    }
}
```

**Typescript** (after **TypeGen -p "Business" generate**)

```
export class CommentDTO {
    id: number;
    message: string;
    answerIds: number[];
    parentId: number;
    activityId: number;
}
```

**Comment by Allov** [comment]
While `parentId?: number` will render the property optional, it's not nullable (like in C#). Should you not be defining it as such: `parentId?: number | null` ?

Exemple:
![image](https://user-images.githubusercontent.com/1179492/75613492-54409b00-5afc-11ea-87d7-104944e11abb.png)

Maybe it's a `tsc` configuration though...

**Comment by Allov** [comment]
I think the setting you're looking for is `csNullableTranslation`. Put that in your `tsconfig.json`

`"csNullableTranslation": "null"`

**Comment by jburzynski** [comment]
> I am only using the attribute in classes in C#, I have not used any additional configuration.
> 
> **C#**
> 
> ```
> using System.Collections.Generic;
> using TypeGen.Core.TypeAnnotations;
> 
> namespace Business
> {
>     [ExportTsClass(OutputDir = @"../Presentation/ClientApp/src/app/models")]
>     public class CommentDTO
>     {
>         public int Id { get; set; }
>         public string Message { get; set; }
>         public ICollection<int> AnswerIds { get; set; }
>         public int? ParentId { get; set; }
>         public int ActivityId { get; set; }
>     }
> }
> ```
> 
> **Typescript** (after **TypeGen -p "Business" generate**)
> 
> ```
> export class CommentDTO {
>     id: number;
>     message: string;
>     answerIds: number[];
>     parentId: number;
>     activityId: number;
> }
> ```

I think optional properties are only allowed in TypeScript interfaces (not TypeScript classes). I've just double-checked this and I couldn't find information about optional properties for TypeScript classes in TypeScript documentation.

But maybe this is allowed, but I just haven't found the information - can you please check if it compiles if you put an optional property in a TypeScript class (or have you found maybe some information in the docs that this is possible)?

If you'd like to generate an optional property in a TypeScript interface, you'd need to use [`TsOptionalAttribute`](https://typegen.readthedocs.io/en/latest/attributes.html#tsoptionalattribute) (or the `.Optional()` method in the generation spec) for the member.

Since the `?` type suffix in C# means the type is nullable, I thought it would be a good idea to translate it to a type union with `null` or `undefined` in TypeScript. As @Allov mentioned, you can choose which TS type union (`null`, `undefined`, both or none) to use for nullable C# types using the `"csNullableTranslation"` config parameter.

An example of `csNullableTranslation`:
- if you put `"csNullableTranslation": "null"` in the config, this will translate `MyValueType?` (the member type) in C# to `MyValueType | null` in TS
- if you put `"csNullableTranslation": "null|undefined"` in the config, this will translate `MyValueType?` (the member type) in C# to `MyValueType | null | undefined` in TS
- if you don't specify `csNullableTranslation` in the config, it will use the default value `""` (which means no type unions are used) and `MyValueType?` (the member type) in C# will translate to `MyValueType` in TS

So C# nullable types are translated to type unions (with `null`, `undefined`, neither or both) in TS;
and to specify an optional property for TS interface, you can use [`TsOptionalAttribute`](https://typegen.readthedocs.io/en/latest/attributes.html#tsoptionalattribute).

**Comment by parloti** [comment]
Thank you guys,

The solution was to use:
```
{
   ...
    parentId: null;
  ...
} as CommentDTO 
```

**Comment by johnknoop** [comment]
Sorry for hijacking the thread, but I'm looking to replace TypeWriter because it doesn't handle nullable reference types in C#. Judging by this thread, TypeGen doesn't automatically translate C# nullables into TS optionals. Is it a simple thing to configure it to do that?

**Comment by elwynelwyn** [comment]
Also bumping old thread  sorry^^

Would love a way to make C# nullable types optional TS properties.
I've set up `csNullableTranslation` to `undefined` which is correctly generating the union type `T | undefined`, however this means you still have to manually specify these properties as when creating these objects.

```
class Car {
    string Model { get; set; }
    Sunroof?: Sunroof { get; set; }
}
```
becomes
```
interface Car {
    model: string;
    sunroof: Sunroof | undefined;
}
```
and now for ever car I define, I must do
```
const car: Car = {
    model: 'some cool car',
    sunroof: undefined
};
```
whereas I would prefer to define all cars without sunroofs like:
```
const car: Car = {
    model: 'some cool car'
};
```
(imagine there are many of these properties which can optionally be used in different situations, and currently I have to set every one of them as undefined).

I'd prefer not to instrument many many C# classes / properties with TypeGen attributes, and instead base it from our existing nullable properties.
(I did try the attribute but it didn't seem to actually work - perhaps because I am using a GenerationSpec? I'm also unable/unwilling to manually set properties as optional in the spec due to there being way too many / not wanting a giant blog of config)

Any other workarounds to suggest?
