### ISSUE TITLE
Is it possible to just specify an input directory and an output directory and have TypeGen just convert as part of the project build?

### ISSUE THREAD

**Issue by ElectricCoffee** [jburzynski/TypeGen#126]
I have a DTO folder with some 150+ files, annotating all of them is fine, it gives the generator clarity in how it should do this, but having to then go and explicitly include each and every one of these files in a generator class and then define explicit output files for each of them is a bit extreme. Is there really no way to automate all of this?
I know MTT can do this, but unfortunately it suffers from a lot of false negatives, converting even `List<string>` to `any[]`.
Is there a way for me to just specify to the generator class that.

a) I want everything in the DTO folder, so I don't have to remember to add each new file to the spec
b) I want all the output sent to the respective `.ts` files on the front-end
c) do this automatically so I don't have to remember to call the conversion command manually

**Comment by jburzynski** [comment]
It's possible to automatically generate all types from a given C# namespace using generation specs, you can have a look at the example on [this docs page](https://typegen.readthedocs.io/en/latest/generationspec.html) that says `// generate types by namespace`. This example can be changed to specify an output directory for the TypeScript files, like this: `AddClass(type, "outputDirectory");`. It's not possible to specify an input *directory* (only *namespace*), because TypeGen doesn't generate from source files - it generates using Reflection, so the folder information is lost.

TypeGen can be added as a build step (for example using the [`dotnet-typegen`](https://www.nuget.org/packages/dotnet-typegen) command), but it only generates the TypeScript files and does not transpile them, so to generate the JavaScript files, a transpiler has to be called in the build after TypeGen.

I think this satisfies the requirements a), b) and c). The only potential problem is that the input *directory* cannot be specified (only the *namespace*) and that a generation spec has to be used (it cannot be done with attributes).

**Comment by ElectricCoffee** [comment]
Unfortunately I no longer work at the place where I required TypeGen to do my job.

Since more than a year has passed since I posted this question, I can tell you that I went through each of the 150 files and added TypeGen decorators to all my interfaces individually.
