### ISSUE TITLE
[Question] Generating TypeScript files from DTOs in a Nuget package

### ISSUE THREAD

**Issue by ryanbuening** [jburzynski/TypeGen#42]
I currently use DTOs provided in a Nuget package that I bring into my front-end project. Is there a way to setup TypeGen to access these DTOs and convert them to TypeScript?

**Comment by ryanbuening** [comment]
Looks possible when creating a GenerationSpec. Closing.

**Comment by jburzynski** [comment]
Yes, it's possible with a GenerationSpec. I'll elaborate slightly on other available options:
- if you're the author of the NuGet package containing DTOs, you can also add TypeGen attributes to your DTOs and then add the path to the assembly with DTOs in the `assemblies` parameter in `tgconfig.json`
- if you already have TypeGen attributes in your DTOs and you just want to generate from an external dll without migrating the entire project to a GenerationSpec (instead of attributes), you can also set the `useAttributesWithGenerationSpec` and `generateFromAssemblies` options to `true` in `tgconfig.json` - this will cause files to be generated from the specified assemblies using attributes, but also the external assembly will be generated from a GenerationSpec specified in `generationSpecs` in `tgconfig.json`
