### ISSUE TITLE
Generated files successfully but not seeing any files

### ISSUE THREAD

**Issue by ryanbuening** [jburzynski/TypeGen#44]
I have TypeGen 2.1.2 package installed and am using version 2.1.2 of the CLI.

I created the GenerationSpec below and added it to the root of my project.

```
    public class MyGenerationSpec : GenerationSpec
    {
        public MyGenerationSpec()
        {
            AddEnum<FarmDTOs.Loss.Causes>();
        }
    }
```

When I run `dotnet typegen generate` I get the following messages:

`Generating files for project "."...`
`Files for project "." generated successfully.`

However, I don't see any files created in my project. Any ideas?

**Comment by jburzynski** [comment]
You need to add your generation spec to `tgconfig.json` (under `generationSpecs` - more info in the docs under [CLI | configuration file | parameter list](https://typegen.readthedocs.io/en/latest/cli.html#configuration-file)) - that's the first thing I can think of that can be the problem.

I have to mention it in every "getting started" guide, because right now it looks like you can just add a spec and generate, but in fact you need to also add the spec to `tgconfig.json`. I'll update all docs that mention that.

**Comment by ryanbuening** [comment]
Got it. Thanks for clarifying.
