### ISSUE TITLE
Index file per folder

### ISSUE THREAD

**Issue by NewDark90** [jburzynski/TypeGen#58]
So, I like the index file generation feature, but it seems like overkill for the number of generated files I have. I wish it was usable on a per folder basis, based on "outDir" string on AddClass/Interface/etc.

**Comment by NewDark90** [comment]
I want to take a swipe at adding in this functionality. When I get the code prepared, do you mind doing a review and possibly tweak it to fix to your exact liking?

**Comment by jburzynski** [comment]
Hi, sorry I didn't respond earlier. Yes, this definitely would be useful.

It would be great if you could make a pull request - I can review it and possibly refactor slightly etc. Thanks!

**Comment by jburzynski** [comment]
If you decide not to do this yourself, I'll add it to todo anyway and it will just be added to the next release.

**Comment by NewDark90** [comment]
I am working on it. Things got weird with work. I'll let you know if I
don't want to handle it. Thanks! 😁

**Comment by jburzynski** [comment]
Cool thanks! :)

**Comment by jburzynski** [comment]
It's released now in version 2.3.3

**Comment by NewDark90** [comment]
Somewhat unrelated, but is there any way to have template service exposed somehow? I'm realizing I'd rather not implement my own methods for generating that content. At least the two methods for generating that content. Maybe passing Func parameters that call the template service? 

Thoughts?

**Comment by NewDark90** [comment]
I'm going to stew on this for a bit I think, let me get you something...

**Comment by jburzynski** [comment]
By the time index file generator is called, template service is already injected - do you mean using the template service inside or outside an index file generator?

**Comment by NewDark90** [comment]
There's a new pull request to look at. Open to all feedback on it

**Comment by jburzynski** [comment]
I just released version 2.4.0, which has new functionality for generating index files (I also removed the currently implemented version, i.e. with specifying an IndexFileProvider).

In short, you add a single barrel file in the generation spec (there's a new `OnBeforeBarrelGeneration` method):

```csharp
public override void OnBeforeBarrelGeneration(OnBeforeBarrelGenerationArgs args)
{
    AddBarrel(string directory, BarrelScope scope); // the scope determines what should a barrel contain (files, directories or both)
}
```

You can also select specific folders by traversing the `GeneratorOptions.BaseOutputDirectory`, because `OnBeforeBarrelGeneration` is invoked when files are already generated - there is more information on this with examples [in the docs](https://typegen.readthedocs.io/en/latest/generationspec.html).

So it's possible to organize barrels however you want pretty much, the only restriction being that a single barrel file cannot exceed the boundary of its directory (it can't contain files or directories from other directories).

I figured this should be enough in most cases, but if there's something more that would be useful to implement, I can add it in future releases.

**Comment by NewDark90** [comment]
You are an absolute champ. Thanks man!

**Comment by jburzynski** [comment]
You're very welcome! :)
