### ISSUE TITLE
TypeGen.Cli high CPU usage

### ISSUE THREAD

**Issue by anortham** [jburzynski/TypeGen#68]
I have a post-build event to run the TypeGen.CLI. This works fine and doesn't create too much of a delay in building from withing VS. I also use NCrunch which is set to ignore post-build events. However when NCrunch runs a new build after a change is detected, the build time increases so much that it sometimes seems to just never finish. Checking task manager shows the TypeGen CLI pegged on one cpu core. Has anyone else seen this?

**Comment by jburzynski** [comment]
Hi,

unfortunately I probably won't have time to look more into this issue over the next few days.

At first glance it looks like the problem may be due to TypeGen taking a long time to find the referenced assemblies. You could try to see what the output says with the verbose setting on and maybe see if it chokes on "attempting to resolve assembly...".

I'll look deeper into it whenever I have some spare time.
