### ISSUE TITLE
Custom class

### ISSUE THREAD

**Issue by viniciusverasdossantos** [jburzynski/TypeGen#69]
Is it possible to create custom class as below?

I have a class in C #:
    public class PromocaoDto 
    {
        public int Codigo { get; set; }
        public decimal Valor { get; set; }
        public int Pontos { get; set; }
        public bool Ativo { get; set; }
        public string ImagemHeader { get; set; }
        public string TextoPromocional { get; set; } 
    }
I want to create two classes, one of which is a serializer that should handle the class:

export class PromocaoDto  {
    Codigo: number;
    Valor: number;
    Pontos: number;
    Ativo: boolean;
    ImagemHeader: string;
    TextoPromocional: string;
}
export class PromocaoDtoSerializer {
  fromJson(json: any): PromocaoDto {
    const entidade = new PromocaoDto(); 
    entidade.Pontos = json.Pontos;
    entidade.Ativo = json.Ativo;
    entidade.ImagemHeader = json.ImagemHeader;
    entidade.TextoPromocional = json.TextoPromocional;
    return entidade;
  }

  toJson(entidade: PromocaoDto): any {
    return { 
      Pontos: entidade.Pontos,
      Ativo: entidade.Ativo,
      ImagemHeader: entidade.ImagemHeader,
      TextoPromocional: entidade.TextoPromocional 
    };
  }
}

**Comment by jburzynski** [comment]
By default only C# properties and fields are translated to TypeScript, but you could create the JSON serializer class yourself if you're using generation specs:

```csharp
public class MyGenerationSpec : GenerationSpec
{
  // adding types etc ...

  public override void OnBeforeBarrelGeneration(OnBeforeBarrelGenerationArgs args)
  {
    string jsonSerializerContent = // here you can iterate through typeof(PromocaoDto).GetProperties() to get fields to serialize for PromocaoDtoSerializer
    
    // ... and then you can save PromocaoDtoSerializer to a file:
    File.WriteAllText(args.GeneratorOptions.BaseOutputDirectory + "[the filename]", jsonSerializerContent);
  }
}
```

An alternative way (if you'd like to save both classes in the same file) would be to use [the \<custom-body\> tag](https://typegen.readthedocs.io/en/latest/otherfeatures.html#preserving-parts-of-a-typescript-file) and type the content of `PromocaoDtoSerializer` inside \<custom-body\> - but this wouldn't be very flexible, because then you can't generate the content based on `PromocaoDto`'s properties.

**Comment by viniciusverasdossantos** [comment]
How to debug?

Em 02/09/2019 05:44, Jacek Burzynski escreveu:

> By default only C# properties and fields are translated to TypeScript, but you could create the JSON serializer class yourself if you're using generation specs:
> 
> public class MyGenerationSpec : GenerationSpec
> {
> // adding types etc ...
> 
> public override void OnBeforeBarrelGeneration(OnBeforeBarrelGenerationArgs args)
> {
> string jsonSerializerContent = // here you can iterate through typeof(PromocaoDto).GetProperties() to get fields to serialize for PromocaoDtoSerializer
> 
> // ... and then you can save PromocaoDtoSerializer to a file:
> File.WriteAllText(args.GeneratorOptions.BaseOutputDirectory + "[the filename]", jsonSerializerContent);
> }
> }
> 
> An alternative way (if you'd like to save both classes in the same file) would be to use the <custom-body> tag [1] and type the content of PromocaoDtoSerializer inside <custom-body> - but this wouldn't be very flexible, because then you can't generate the content based on PromocaoDto's properties. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1]
https://typegen.readthedocs.io/en/latest/otherfeatures.html#preserving-parts-of-a-typescript-file
[2]
https://github.com/jburzynski/TypeGen/issues/69?email_source=notifications&amp;email_token=AD6IOZD65F7E2IQ3D77XFPLQHTG6NA5CNFSM4ISVUJ42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5VEW7I#issuecomment-527059837
[3]

**Comment by jburzynski** [comment]
One way would be to download TypeGen source code and debug TypeGen.Cli - it should then hit breakpoints inside generation spec classes as well.

I'm not sure if it's possible to attach debugger process to TypeGen, because TypeGen finishes very quickly, but maybe there is some way to define the name of the process to attach to beforehand - although I'm not sure about this, I haven't tried it.

I personally haven't thought about this so far, because I'm always running TypeGen from the IDE, but it would also be nice to document some nice way of debugging it.

So if you find some easy way of debugging TypeGen without having the source code, I'd appreciate it very much if you share it here. I'll also try to find something and put it in the docs if I find something useful.
