### ISSUE TITLE
"Could not load type" Error

### ISSUE THREAD

**Issue by Aaron-Pool** [jburzynski/TypeGen#70]
I'm attempting to load types from a 4.72 framework project using the dotnet-typegen cli tool.

So, I guess my first question right off the bat is, can I do that? It worked for the first few `.dll`s I threw at it. And it was preferable to the older legacy package manager console tool, because then I could run it in my npm scripts.

Assuming I _can_ use the dotnet-typegen tool for 4.72 projects, here's my situation:

First, I had this in my `tgconfig.json`:
```json
{
    "assemblies": [
        "./Res.Proposals.Api/bin/Local/net472/RES.Proposals.Api.dll",
        "./Res.Proposals.Api/bin/Local/net472/RES.Proposals.Domain.dll",
    ],
    "externalAssemblyPaths": [
        "./RES/bin/net472/RES.dll"
    ],
    "enumStringInitializers": true,
    "outputPath": "./RES.Web/frontend/src/types",
    "singleQuotes": true,
    "propertyNameConverters": [],
    "filenameConverters": [],
    "clearOutputDirectory": true
}
```

I run `dotnet-typegen generate` and everything worked great, I got this output:

```
Generated [x].ts
Generated [y].ts
Generated [z].ts
...yada yada and then...
Files for project "." generated successfully.
```

Boom, everything was great. But then I actually wanted to add an enum from our core library, so I added a single TSExportEnum attribute and I moved the dll from externalAssemblyPath to my assemblies list, like so:
```json
{
    "assemblies": [
        "./Res.Proposals.Api/bin/Local/net472/RES.Proposals.Api.dll",
        "./Res.Proposals.Api/bin/Local/net472/RES.Proposals.Domain.dll",
        "./RES/bin/net472/RES.dll"
    ],
    "enumStringInitializers": true,
    "outputPath": "./RES.Web/frontend/src/types",
    "singleQuotes": true,
    "propertyNameConverters": [],
    "filenameConverters": [],
    "clearOutputDirectory": true
}
```

And suddenly we got problems.

```bash
Could not resolve assembly: System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 in any of the searched directories: C:\Users\apv\.nuget\packages\; C:\Program Files\dotnet\sdk/NuGetFallbackFolder; C:\Program Files\dotnet\shared
Could not resolve assembly: System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 in any of the searched directories: C:\Users\apv\.nuget\packages\; C:\Program Files\dotnet\sdk/NuGetFallbackFolder; C:\Program Files\dotnet\shared
Could not resolve assembly: System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 in any of the searched directories: C:\Users\apv\.nuget\packages\; C:\Program Files\dotnet\sdk/NuGetFallbackFolder; C:\Program Files\dotnet\shared
Could not resolve assembly: System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 in any of the searched directories: C:\Users\apv\.nuget\packages\; C:\Program Files\dotnet\sdk/NuGetFallbackFolder; C:\Program Files\dotnet\shared
Could not resolve assembly: System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 in any of the searched directories: C:\Users\apv\.nuget\packages\; C:\Program Files\dotnet\sdk/NuGetFallbackFolder; C:\Program Files\dotnet\shared
Could not resolve assembly: System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in any of the searched directories: C:\Users\apv\.nuget\packages\; C:\Program Files\dotnet\sdk/NuGetFallbackFolder; C:\Program Files\dotnet\shared
Could not resolve assembly: System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in any of the searched directories: C:\Users\apv\.nuget\packages\; C:\Program Files\dotnet\sdk/NuGetFallbackFolder; C:\Program Files\dotnet\shared
Could not resolve assembly: System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in any of the searched directories: C:\Users\apv\.nuget\packages\; C:\Program Files\dotnet\sdk/NuGetFallbackFolder; C:\Program Files\dotnet\shared
Could not resolve assembly: System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 in any of the searched directories: C:\Users\apv\.nuget\packages\; C:\Program Files\dotnet\sdk/NuGetFallbackFolder; C:\Program Files\dotnet\shared
Could not resolve assembly: System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 in any of the searched directories: C:\Users\apv\.nuget\packages\; C:\Program Files\dotnet\sdk/NuGetFallbackFolder; C:\Program Files\dotnet\shared
GENERIC ERROR: Could not load type 'System.ServiceModel.ServiceContractAttribute' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType
attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
   at TypeGen.Core.Extensions.TypeExtensions.HasExportAttribute(Type type, IMetadataReader reader) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Extensions\TypeExtensions.cs:line 26
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at TypeGen.Core.Generator.Services.GenerationSpecProvider.GetGenerationSpec(IEnumerable`1 assemblies) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator\Services\GenerationSpecProvider.cs:line 28
   at TypeGen.Core.Generator.Generator.Generate(IEnumerable`1 assemblies) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 305
   at TypeGen.Cli.Program.Generate(String projectFolder, String configPath) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 137
   at TypeGen.Cli.Program.Main(String[] args) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 70
```
I don't know why it's trying to resolve all of those `Version=0.0.0.0` packages, first of all. I searched my solution for them, and I can't find any such dependency. I even have the following reference in my `.csproj`
```
<PackageReference Include="System.Configuration.ConfigurationManager" Version="4.5.0" />
```
The biggest problem is the final error, which totally kills the script though. `could not load type`. That `System.ServiceModel.ServiceContract` is building just fine, so I don't know why the typegen script is choking on it 🤷‍♂

**Comment by jburzynski** [comment]
Hi,

`externalAssemblyPaths` are directories that contain assemblies referenced by the assemblies you're generating types from. By default TypeGen searches for any referenced assemblies in 3 directories: the NuGet packages folder (in this case `C:\Users\apv\.nuget\packages\`), the NuGet fallback folder (in this case `C:\Program Files\dotnet\sdk/NuGetFallbackFolder`) and in the .NET shared folder (in this case `C:\Program Files\dotnet\shared`), as these are usually the external folders in which NuGet packages are stored.

If your assembly references another assembly that is in an external directory and this referenced assembly is not in any of the 3 directories listed above, you need to explicitly add the directory containing the referenced assembly to `externalAssemblyPaths`, so that TypeGen knows where to look for it when resolving assembly dependencies (an assembly can only be loaded if all of its dependencies/references are resolved).

So in the first example, the `./RES/bin/net472/RES.dll` in `externalAssemblyPaths` has no effect on the generation, because it's not a directory. It would make sense to add `./RES/bin/net472` to `externalAssemblyPaths` if any of the assemblies in the `assemblies` parameter referenced `RES.dll`, but I assume it's not the case here.

Also, I'm not sure how NuGet dependencies are added in .NET/ASP.NET 4.72. If they're added to the "global" NuGet folder (`C:\Users\...\.nuget\packages\`), TypeGen should be able to automatically resolve them. If they're added somewhere else (e.g. in the project/solution directory), you may have to add the NuGet folder to `externalAssemblyPaths`.

In general, it looks to me that the error might be thrown because some of the assemblies referenced by `RES.dll` (`System.Configuration.ConfigurationManager`, `System.Data.SqlClient` and possibly others) are not in the same folder as `RES.dll` and are not located in any of the 3 directories searched by TypeGen and therefore `RES.dll` cannot be loaded.

As for the `Version=0.0.0.0`, I know .NET Standard references assemblies in version `0.0.0.0` to avoid assembly loading problems and perhaps .NET Framework is doing the same - but I'm not completely sure about it.

**Comment by Aaron-Pool** [comment]
@jburzynski

First of all, thanks for getting back to me.

Secondly, while the initial series of "could not resolves" are annoying, and I would like to get rid of them I've actually gotten those errors before and the type generating still finished as expected. In fact, that was why I added `RES.dll` to my external assemblies in the first place. For the first two projects, the type generation was working, but it was throwing an error about not finding an assembly from the `RES` project. So I added the full as external and it went away.

The bigger problem here is the last error, which actually causes the whole process to die:

```Could not load type 'System.ServiceModel.ServiceContractAttribute' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'```

Which seems to imply that it even resolved the type, but it couldn't load it. Any insight on this? I honestly don't care about the file it's dying on, is there any way I can have typegen ignore it completely? There's only a very small sunset of files I care about in RES.dll, is there any way I can just parse a subset of files from the dll, or will it try to parse the whole thing no matter what?

**Comment by jburzynski** [comment]
I found these 2 threads: [stack overflow](https://stackoverflow.com/questions/50730878/could-not-load-file-or-assembly-system-servicemodel-version-4-0-0-0-exception) and one on [github](https://github.com/dotnet/standard/issues/575). I'm not sure if you've found them as well. Have you maybe tried installing the `System.ServiceModel.*` NuGet packages?

I'm not sure if you can load only a part of an assembly / certain types etc. with reflection. As I remember, if you don't provide all referenced assemblies, it will not be able to load the assembly that you're trying to load.

**Comment by Aaron-Pool** [comment]
So. Those packages are installed (to the best of my knowledge). Could this have anything to do with it being a 4.7.2 package and I'm running the latest version of the cli? Or does that not matter?

**Comment by jburzynski** [comment]
In terms of loading .NET Framework assemblies in .NET Core, I know you can load a .NET Framework assembly in .NET Core if it supports lower .NET Standard version than what the .NET Core version you're using supports (because I've actually tried it :) ).

It would seem that since both .NET Core 2.2 and .NET Framework 4.7.2 implement .NET Standard 2.0, you should be able to load a .NET Framework 4.7.2 assembly from the TypeGen CLI (which is .NET Core 2.2).

But probably the best way to check it would be to try to test this scenario on some sample projects and see if it works :)

I think one additional reason for the `Could not load type` error could be that the wrong `System.ServiceModel` assembly is being loaded - e.g. it's being loaded from the GAC or something similar.

**Comment by Aaron-Pool** [comment]
Ok. I'll look into it a bit more, see if I can figure out for sure which assembly it's loading, thanks for the follow up 👍

**Comment by jburzynski** [comment]
Sure no problem :thumbsup:

**Comment by Aaron-Pool** [comment]
Nevermind, once I realized that, I was able to figure out the problem myself. For anyone in the future using this, if you're getting an error about a assembly not being found, make sure it's not coming from GAC, and, if it is, add
```json
"externalAssemblyPaths": [
    "C:/windows/Microsoft.Net/assembly"
]
```
And you'll be good 👍

**Comment by jburzynski** [comment]
No problem, glad I could help with something :) I'm happy it got resolved and you managed to find a solution, and thanks for posting it!
