### ISSUE TITLE
The CLI package is not compatible with DotNet core 3.0

### ISSUE THREAD

**Issue by agustinbcu01** [jburzynski/TypeGen#71]
The CLI package is not compatible with DotNet core 3.0.

Because the dotnetTool package.
``` 
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package TypeGen.DotNetCli 2.4.2 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package TypeGen.DotNetCli 2.4.2 supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2) / any	TypegenTest	C:\Users\agust\Source\Repos\TypegenTest\TypegenTest\TypegenTest.csproj	1	

```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Package 'TypeGen.DotNetCli 2.4.2' has a package type 'DotnetTool' that is not supported by project 'TypegenTest'.				
```

**Comment by jburzynski** [comment]
Have you perhaps added the `TypeGen.DotNetCli` package to your project?

The `TypeGen.DotNetCli` package is a .NET Core CLI tool, which should only be used in this context - this means it should not be added to a project.

Only the `TypeGen` NuGet package should be added to a project.

Having said that, I will also update TypeGen to .NET Core 3.0.

**Comment by agustinbcu01** [comment]
Thanks you.

Not upgrading to dotnet core until most people uses is not a good police, because that police prevent people to fully upgrade.

The idea of the code generator tool is to help with the dev process.

Regards

**Comment by jburzynski** [comment]
Glad I could help 👍 

You can still use TypeGen with .NET Core 3 as long as you're not using features specific to .NET Core 3 inside of the types you're generating, which right now is probably the vast majority of the cases. If I upgrade, however, this would prevent people who use lower versions of .NET from using the newest TypeGen (and since the stable release of .NET Core 3 was a week ago, I felt that this would still be a lot of people). So just weighting the pros and cons I thought I'll change the version of TypeGen in like 2-3 weeks so that the majority of people will have had the chance to upgrade by this time, but at the same time until TypeGen is upgraded, people who use .NET Core 3 could still use TypeGen, because they're most likely not using the latest features inside the types they're generating.

So at this point I'll just wait a couple of days until most people have the chance to switch to .NET Core 3 and I'll upgrade the version :) You're right though that if the upgrade was delayed for too long, this would be bad, because TypeGen is a dev tool and it should allow you to use the latest features.

**Comment by agustinbcu01** [comment]
Great:

I'm know is more time consuming, but multi target platform is possible.
And some new features can be enable/disables depending the target.

https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks

Regards.

**Comment by jburzynski** [comment]
Thanks, I'll look more into this!

**Comment by jburzynski** [comment]
.NET Core 3.0 support added in version 2.4.7. If something doesn't work, please write in this issue.
