### ISSUE TITLE
Convert C# class in .ts enum

### ISSUE THREAD

**Issue by fabiomaistro** [jburzynski/TypeGen#79]
As a future implementation, it would be very useful to have a way to convert a C# class having string constants like this:

```cs
public static class Categories
    {
        public const string Cars = "cars";
        public const string Toys = "toys";
    }
```

into string enum in TypeScript:

```ts
export enum Categories {
    Cars = "cars",
    Toys = "toys"
}
```

**Comment by jburzynski** [comment]
I've been thinking lately about implementing more customization for how to generate things. E.g. allow to load some custom logic that specifies how to generate certain parts etc.

I guess this example is somewhat "non-standard" and there is potentially a lot of quite similar examples of the requirements that someone might need (and which are not available out of the box), that's why I thought the best solution would be to allow for some more customization than just the config parameters (like loading your custom logic in C# or something more like that).

But this is just a plan right now and it might take some time to implement, so I'm not expecting it to happen in the nearest future.

If you decide to make a fork and try to implement some solution that solves your problem, I would be very interested to see the implementation. But for now I think there will be unfortunately no out-of-the-box solution in the nearest future.
