### ISSUE TITLE
KeyValuePair conversion

### ISSUE THREAD

**Issue by Pauline3** [jburzynski/TypeGen#85]
Hi, 
I have a class with a KeyValuePair member.

When I try to generate the ts class, I have the following error : 
_APPLICATION ERROR: Generated type must be either a C# class or enum. Error when generating type System.Collections.Generic.KeyValuePair_

I tried to change the Type in tgconfig by adding a customTypeMapping but it doesn't work : 
 _"customTypeMappings":{"System.Collections.Generic.KeyValuePair":"Object"},_

Is there a way to convert KeyValuePair ?

**Comment by jburzynski** [comment]
This is a bug, because customTypeMappings should allow to map struct types. I'll look at it whenever I have some spare moment.

Right now a workaround (if you don't have a lot of properties like that) could be to ignore the struct members and add them manually using the <custom-body> tag in the .ts file. It's described more in the docs in "other features" ("preserving parts of a typescript file").

**Comment by jburzynski** [comment]
Actually now I realised 1 more thing that could help (I haven't tried it though): can you try with KeyValuePair`2 (instead of just KeyValuePair without arity)?

**Comment by Pauline3** [comment]
I can't change the code which contains the KeyValuePair.
I will use your first proposition (with the costom-body).

**Comment by jburzynski** [comment]
I think my message maybe was a bit vague: I was thinking about changing the customTypeMappings in tgconfig to map KeyValuePair`2 instead of just KeyValuePair (I think this type is generic and has 2 generic parameters, that's why I thought maybe this would work).

So if you want you could try this - or maybe I understood your comment wrong and that's what you actually tried :)

**Comment by Pauline3** [comment]
You are right, I did not understand your previous message.
I tried to change the tgconfig, but it did not work :
"customTypeMappings": {
    "System.Collections.Generic.KeyValuePair`2": "Object"
  },

**Comment by jburzynski** [comment]
Ok, I'll add it to the things to fix for the next release then.
I'm not really sure when exactly I'll be able to do the release, because lately I haven't had a lot of time for TypeGen.
But I'll do it as soon as I can :)

**Comment by Pauline3** [comment]
ok, thank you :-)

**Comment by jburzynski** [comment]
Hi,

sorry for quite a late response!

It looks like I probably won't have too much free time to do TypeGen in the nearest future, so for a while I'll only be merging pull requests.

There is one more topic #89 also about customTypeMappings not working for generic types which may potentially result in a pull request that would fix it.

If you decide to do your own pull request related to this issue, I think it may be a good idea to consult it with @bcrosnier so that the work isn't duplicated.

**Comment by jburzynski** [comment]
Hi, just an update that generic types should now be supported for `customTypeMappings` in version 2.4.9 (just released).

You should be able to either map a generic C# type to a non-generic TypeScript type:
```json
"customTypeMappings": {
"System.Collections.Generic.KeyValuePair`2": "Object"
}
```

or map a generic C# type to a generic TypeScript type (the generic parameters will be copied from the C# type):
```json
"customTypeMappings": {
"System.Collections.Generic.KeyValuePair`2": "TsKeyValuePair<>"
},
```

If you try it, could you please let me know if it works? Thanks!

**Comment by jburzynski** [comment]
Closed due to inactivity
