### ISSUE TITLE
DotnetToolReference

### ISSUE THREAD

**Issue by Wyren** [jburzynski/TypeGen#88]
I got an error when trying to install the "dotnet-typegen" package via de package manager and de dotnet cli.
It seems to be related to this issue: https://github.com/NuGet/Home/issues/4190

> C:\Users\ \*\source\repos\proj.WebApi\proj.WebApi\proj.WebApi.csproj : error NU1202: Package dotnet-typegen 2.4.7 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package dotnet-typegen 2.4.7 supports:
C:\Users\ \*\source\repos\proj.WebApi\proj.WebApi\proj.WebApi.csproj : error NU1202:   - netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
C:\Users\ \*\source\repos\proj.WebApi\proj.WebApi\proj.WebApi.csproj : error NU1202:   - netcoreapp2.2 (.NETCoreApp,Version=v2.2) / any
C:\Users\ \*\source\repos\proj.WebApi\proj.WebApi\proj.WebApi.csproj : error NU1202:   - netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any
C:\Users\ \*\source\repos\proj.WebApi\proj.WebApi\proj.WebApi.csproj : error NU1212: Invalid project-package combination for dotnet-typegen 2.4.7. DotnetToolReference project style can only contain references of the DotnetTool type

Using the install command "dotnet tool install --global dotnet-typegen --version 2.4.7" and the TypeGen package solved this well enough. But the error from NuGet doesn't help to get to that solution. :-)

FYI: https://github.com/NuGet/Home/wiki/Global-Tools---NuGet-Implementation

**Comment by jburzynski** [comment]
Hi,
sorry for my late reply.

I'll look into this more when I get a moment - but unfortunately lately I haven't had a lot of time to work on TypeGen, so I couldn't say when exactly I'll manage to fix this.

Thanks

**Comment by jburzynski** [comment]
So when you used the `TypeGen` NuGet package for the project and `typegen-dotnet` for the .NET CLI tool it worked?
I think the error in your original post usually happens when you try to install the `dotnet-typegen` package (not `TypeGen`) for a project. This fails, because it's a .NET Core CLI tool and the package to install to a project is `TypeGen`.
Please let me know if this means your problem is fixed.

**Comment by stephtr** [comment]
I noticed a similar issue while dealing with projects from a previous version of .NET Core which includes
`<DotNetCliToolReference Include="TypeGen.DotNetCli" Version="1.6.4" />` as an item within the csproj file. With 1.6.4 and .NET Core 3.1 that entry restores, but updating it to 2.4.7 fails with the error @Wyren wrote.
As @Wyren stated one can either install the tool as a global tool, but starting with .NET Core 3.0 there's also a new feature of [local tools](https://andrewlock.net/new-in-net-core-3-local-tools/). For me both methods work, hence I can't see any issue.

**Comment by Wyren** [comment]
> So when you used the `TypeGen` NuGet package for the project and `typegen-dotnet` for the .NET CLI tool it worked?
> I think the error in your original post usually happens when you try to install the `dotnet-typegen` package (not `TypeGen`) for a project. This fails, because it's a .NET Core CLI tool and the package to install to a project is `TypeGen`.
> Please let me know if this means your problem is fixed, thanks :)

I installed TypeGen as a package, but if I work with VS Code I can use the CLI tools because dotnet doesn't know TypeGen as a command. In the previous Wiki it stated I should install dotnet-typegen to allow a local use of the tool. This produces the error I mentioned. It's related to @stephtr s' comment. However I could find a way to get it to work as a local tool, apart from fixing the path issue myself with a bash script. Which isn't a solution I prefer.

> As Wyren stated one can either install the tool as a global tool, but starting with .NET Core 3.0 there's also a new feature of local tools. For me both methods work, hence I can't see any issue (anymore).

I'll look into the link. If it's a bit of work to get it to work as a local tool that would solve the issue. I'd prefer it if I didn't have a hidden dependency and could confine the tool to the project I'm using it for.

FYI, this is also the reason your build street isn't succeeding anymore.

**Comment by Wyren** [comment]
It might be a good addition to the doc's to reference the link @stephtr mentioned in case people want to use TypeGen with VS Code and as a local tool. I'm not sure where to put it best in the doc's, so I'm a bit hesitant to put it somewhere. 😅

**Comment by jburzynski** [comment]
Older docs I think did say that you can use dotnet-typegen as a local tool - it shouldn't say this anymore, because this was not the case (I'm of course talking about the "old" local tools).

I think it would be useful to add the info that for .NET Core older than 3.0 you can't use dotnet-typegen as a local tool - it seems that right now the docs don't specify whether dotnet-typegen can be used as a local or global tool - it just says ".NET Core CLI tool". I'll include this information somewhere.

But it's pretty nice that you can now use the "global" tools as "local" tools too. I'm glad this worked out!
