### ISSUE TITLE
Support struct types

### ISSUE THREAD

**Issue by themre** [jburzynski/TypeGen#90]
hi,
first thing, thanks for this library! is there a way to support struct types? thanks!

**Comment by jburzynski** [comment]
Hi,

I'm glad it's useful!

I tried to add support for structs some time ago, but it turned out that with the current "architecture" it would require a bit more time to implement this.

I recently haven't had a lot of time to actively develop TypeGen, but you're more than welcome to make a pull request if you'd like to add this functionality yourself!

I have struct support on my "todo" list (together with a couple of other things), but unfortunately I can't say when I would be able to (/ have some time to) implement it.

Sorry I couldn't help more with this. I guess to sum up, this functionality is just waiting for either me or someone else to implement, but it's not easy to say when this will happen.

**Comment by themre** [comment]
hi,
thanks for the answer, i completely understand. do you perhaps have some
guides where to start adding support for structs? sorry to ask such lame
question, i'm not much of a .NET programmer :)

V ned., 22. dec. 2019 00:13 je oseba Jacek Burzynski <
notifications@github.com> napisala:

**Comment by jburzynski** [comment]
That's a good question :)

The class that generates the files is [TypeGen.Core.Generator.Generator](https://github.com/jburzynski/TypeGen/blob/master/src/TypeGen/TypeGen.Core/Generator/Generator.cs) and it uses some [service classes](https://github.com/jburzynski/TypeGen/tree/master/src/TypeGen/TypeGen.Core/Generator/Services) to do particular bits of work. To be honest, that's about everything these is to the architecture :)

All file generation logic is in TypeGen.Core; TypeGen.Cli just uses the Generator class from TypeGen.Core to generate files.

I tried to add as much documentation comments as possible, so the purpose of a particular class/method should be in its xmldoc (the comment directly above the class/method name).

I think the best way to start working on this would be to look at [the Generator class](https://github.com/jburzynski/TypeGen/blob/master/src/TypeGen/TypeGen.Core/Generator/Generator.cs) and then look at the classes referenced by it (mostly the service classes from [TypeGen.Core.Generator.Services](https://github.com/jburzynski/TypeGen/tree/master/src/TypeGen/TypeGen.Core/Generator/Services)) and then go further from there.

You can see the usage of the Generator class in [TypeGen.Cli.Program (line 126)](https://github.com/jburzynski/TypeGen/blob/master/src/TypeGen/TypeGen.Cli/Program.cs#L126) to better understand how it's used.

If you create a pull request, I'll be able to merge it after new year. Hope this helps a bit :)

**Comment by jburzynski** [comment]
Since this is already in the todo list, this issue can be closed.

**Comment by parksj10** [comment]
hi @jburzynski , wondering where this is at on your TODO list? would be useful for me too...

**Comment by Cluster7ck** [comment]
I took a crack at it in #154
