### ISSUE TITLE
Error when running dotnet-typegen generate on version  2.4.8 and .Net core 3.1

### ISSUE THREAD

**Issue by ShadySadek** [jburzynski/TypeGen#96]
Hi,
We are running the dotnet-typegen -v generate as a post build event script. With every project/solution build we are facing some slowness and we are getting "Could not resolve assembly" errors on the visual studio output screen:
![image](https://user-images.githubusercontent.com/10491559/74732067-675b8d00-5217-11ea-9392-3786a0ec7705.png)

We  have .NET Core 3.1 in similar versions. Here is the tgconfig.json
{
  "generationSpecs": [ "TypeGenSpec" ],
  "outputPath": "ClientApp/src/models/generated",
  "fileNameConverters": [ "CustomNameConverter" ],
  "typeNameConverters": [ "CustomNameConverter" ],
  "csNullableTranslation": "null",
  "tabLength": 2,
  "singleQuotes": false,
  "clearOutputDirectory": true,
  "customTypeMappings": {
    "System.DateTime": "string"
  },
  "typeUnionsForTypes": {
    "string": [ "null" ]
  }
}

We tried:
-Uninstalling the  tool and installing it (VS and machine was reboot in between)
-nuget locals --clear all
-Using "assemblies" in tgconfig.json
-Running "dotnet-typegen -v" command outside of visual studio on cmd

Thanks

**Comment by jburzynski** [comment]
Hi,

I'm not sure if this could be the reason, but it may be because TypeGen 2.4.8 only supported .NET Core 3.0 (not .NET Core 3.1).

I added .NET Core 3.1 support in version 2.4.9. If you try it, could you please let me know if it works? Thanks.

**Comment by ShadySadek** [comment]
Hi
Thanks for your response.
I Installed 2.4.9 and cleaned and rebuild the project but unfortunately still have the same issue.
Do you have any other suggestion could I do?

Thanks

**Comment by jburzynski** [comment]
Could you please tell me if the files are generated despite the errors? Or the errors happen and no files are generated?

At one project I had a similar situation: there was a lot of 'Could not resolve...' errors, but the files would get generated despite the errors, that's why I wanted to make sure if it's this kind of situation.

But as for the errors, I'm not sure why the assemblies are not found. Maybe there are some additional folders that should be searched, but I haven't looked into it too much.

**Comment by ShadySadek** [comment]
Yes the files are generated despite the errors,

**Comment by jburzynski** [comment]
At the moment I'm not sure if there is a way to solve these errors.

TypeGen searches for the referenced assemblies, because they may be needed when generating the files.

I guess some additional mechanism would have to be implemented to save the time spent on searching these assemblies.

But at the moment I'm not sure how this could be fixed, so maybe this issue can remain open until it's resolved.

**Comment by ExcaliburVT** [comment]
I'm having the same issue with TypeGen 2.4.9 and .Net Core 3.1 

All of my viewmodels are in an external assembly from my web project and i'm getting this error (along with a bunch more) trying to load the assemblies:

Could not resolve assembly: XXXXXXX.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in any of the searched directories: C:\Users\sykesb\.nuget\packages\; C:\Program Files\dotnet\sdk/NuGetFallbackFolder; C:\Program Files\dotnet\shared

I note that the /bin directory is not in this list.  I've definitely compiled and i'm running the command from the local web project directory.

**Comment by jburzynski** [comment]
I've added this to my todo list and will queue it for fixing, so I'm closing this issue.

**Comment by pdsrebelo** [comment]
Sorry for re-opening this issue, but there's a way for you to accomplish what you need @ExcaliburVT 

On your tgconfig.json, just add an "assemblies" array.

Example
`{
  "assemblies": [ "path/to/website.dll", "path/to/domain.dll" ],
  "generationSpecs": [ "TypescriptGenerationSpec" ]
}`

It should generate the .ts files nicely for you :)

P.S. - Yes, I'm also using .NET Core 3.1 and TypeGen 2.4.9.

**Comment by johnknoop** [comment]
I'm getting the same error, but in my case no files are generated.
